import {
  Mission,
  DailyCycleConfig,
  WeeklyMilestoneConfig,
  MissionGuardrailConfig,
  MissionViolation,
  LearnerMissionProgressSample,
} from './types';

export const INITIAL_MISSIONS: Mission[] = [
  // ----------------------------------------------------
  // DAILY MISSIONS POOL (5 MANDATORY SLOTS + BONUS)
  // ----------------------------------------------------

  // Slot 1: Scan & Capture (AI Camera)
  {
    id: 'ms-d-01',
    code: 'MS-D-01',
    title: 'Quét 3 đồ vật quanh bạn (AI Camera)',
    description: 'Sử dụng AI Camera nhận diện và lưu tối thiểu 3 từ vựng mới vào sổ tay.',
    type: 'daily',
    category: 'SCAN_CAPTURE',
    actionType: 'SCAN_OBJECT',
    triggerEvent: 'WORD_SCANNED_AND_SAVED',
    aggregationType: 'COUNT',
    completionRule: {
      requireSavedWord: true,
      uniqueWordOnly: false,
    },
    navigationParams: {
      targetScreen: 'CAMERA_SCAN',
      ctaLabel: 'Mở Camera AI',
    },
    minimumSupportedClientVersion: 'v1.0.0',
    targetCount: 3,
    unit: 'lượt scan có lưu từ',
    difficulty: 'easy',
    reward: { xp: 40, coins: 60 },
    weight: 95,
    status: 'active',
    targetAudience: 'all',
    isBonus: false,
    version: 1,
    completionRate: 84.5,
    claimRate: 78.2,
    totalCompletedCount: 1420,
    totalClaimedCount: 1315,
    lastUpdated: '2026-09-09 10:30',
    updatedBy: 'Lead Admin Hoà',
    auditNotes: 'Nhiệm vụ signature của SnapVocab, gắn điều kiện F-GAME-11 chống spam ảnh trống',
  },

  // Slot 2: Vocabulary Building
  {
    id: 'ms-d-03',
    code: 'MS-D-03',
    title: 'Học 5 từ mới trong chủ đề bất kỳ',
    description: 'Khám phá và ghi nhớ 5 từ vựng mới thuộc danh mục Topics & Decks.',
    type: 'daily',
    category: 'VOCAB_BUILDING',
    actionType: 'LEARN_NEW_WORDS',
    triggerEvent: 'FLASHCARD_REVIEWED',
    aggregationType: 'COUNT',
    completionRule: {
      uniqueWordOnly: true,
    },
    navigationParams: {
      targetScreen: 'FLASHCARD_STUDY',
      ctaLabel: 'Chọn Chủ Đề Học',
    },
    minimumSupportedClientVersion: 'v1.0.0',
    targetCount: 5,
    unit: 'từ mới',
    difficulty: 'medium',
    reward: { xp: 50, coins: 80 },
    weight: 85,
    status: 'active',
    targetAudience: 'all',
    isBonus: false,
    version: 1,
    completionRate: 68.4,
    claimRate: 62.0,
    totalCompletedCount: 980,
    totalClaimedCount: 890,
    lastUpdated: '2026-09-07 09:00',
    updatedBy: 'Lead Admin Hoà',
  },

  // Slot 3: Flashcard & SRS Review
  {
    id: 'ms-d-02',
    code: 'MS-D-02',
    title: 'Ôn tập 15 thẻ từ vựng đến hạn (SRS)',
    description: 'Hoàn thành lượt ôn tập thuật toán lặp ngắt quãng trong ngày.',
    type: 'daily',
    category: 'FLASHCARD_SRS',
    actionType: 'REVIEW_SRS',
    triggerEvent: 'SRS_REVIEW_COMPLETED',
    aggregationType: 'COUNT',
    completionRule: {
      clearSnapshotOnly: true,
    },
    navigationParams: {
      targetScreen: 'SRS_REVIEW',
      ctaLabel: 'Vào Hàng Đợi Ôn Tập',
    },
    minimumSupportedClientVersion: 'v1.0.0',
    targetCount: 15,
    unit: 'thẻ flashcard',
    difficulty: 'easy',
    reward: { xp: 35, coins: 50 },
    weight: 90,
    status: 'active',
    targetAudience: 'all',
    isBonus: false,
    version: 1,
    completionRate: 79.1,
    claimRate: 72.8,
    totalCompletedCount: 1320,
    totalClaimedCount: 1215,
    lastUpdated: '2026-09-08 14:15',
    updatedBy: 'Admin Content',
  },

  // Slot 4: Quiz & Accuracy Testing
  {
    id: 'ms-d-04',
    code: 'MS-D-04',
    title: 'Đạt điểm tối đa (100%) trong 1 bài Quiz',
    description: 'Vượt qua bài trắc nghiệm kiểm tra nhanh mà không mắc lỗi sai nào.',
    type: 'daily',
    category: 'QUIZ_ACCURACY',
    actionType: 'QUIZ_PERFECT',
    triggerEvent: 'QUIZ_COMPLETED',
    aggregationType: 'PERCENTAGE',
    completionRule: {
      minAccuracyPercent: 100,
    },
    navigationParams: {
      targetScreen: 'QUIZ_SETUP',
      ctaLabel: 'Bắt Đầu Làm Quiz',
    },
    minimumSupportedClientVersion: 'v1.0.0',
    targetCount: 1,
    unit: 'bài quiz 100%',
    difficulty: 'hard',
    reward: { xp: 60, coins: 100 },
    weight: 75,
    status: 'active',
    targetAudience: 'intermediate',
    isBonus: false,
    version: 1,
    completionRate: 52.3,
    claimRate: 49.8,
    totalCompletedCount: 750,
    totalClaimedCount: 712,
    lastUpdated: '2026-09-06 16:40',
    updatedBy: 'Admin Gamification',
  },

  // Slot 5: Retention & Personal Gamification
  {
    id: 'ms-d-05',
    code: 'MS-D-05',
    title: 'Nghe luyện phát âm 10 từ chuẩn bản xứ',
    description: 'Nghe phát âm chuẩn US/UK bằng công nghệ TTS trong Content Studio hoặc Flashcard.',
    type: 'daily',
    category: 'RETENTION_GAMIFICATION',
    actionType: 'LISTEN_AUDIO',
    triggerEvent: 'AUDIO_LISTENED',
    aggregationType: 'COUNT',
    completionRule: {
      uniqueWordOnly: true,
    },
    navigationParams: {
      targetScreen: 'HOME_HUB',
      ctaLabel: 'Mở Thư Viện Từ Vựng',
    },
    minimumSupportedClientVersion: 'v1.0.0',
    targetCount: 10,
    unit: 'lượt nghe audio',
    difficulty: 'easy',
    reward: { xp: 30, coins: 40 },
    weight: 80,
    status: 'active',
    targetAudience: 'all',
    isBonus: false,
    version: 1,
    completionRate: 88.2,
    claimRate: 82.5,
    totalCompletedCount: 1540,
    totalClaimedCount: 1440,
    lastUpdated: '2026-09-09 11:20',
    updatedBy: 'Admin Content',
  },

  // Bonus Slot: Duy trì chuỗi Streak (+1 Bonus)
  {
    id: 'ms-d-06',
    code: 'MS-D-06',
    title: 'Nhiệm vụ thưởng thêm: Duy trì chuỗi Streak hôm nay',
    description: 'Hoàn thành ít nhất một hoạt động học tập để bảo toàn ngọn lửa Streak.',
    type: 'daily',
    category: 'RETENTION_GAMIFICATION',
    actionType: 'MAINTAIN_STREAK',
    triggerEvent: 'STREAK_MAINTAINED',
    aggregationType: 'COUNT',
    completionRule: {},
    navigationParams: {
      targetScreen: 'STREAK_DETAIL',
      ctaLabel: 'Xem Chuỗi Streak',
    },
    minimumSupportedClientVersion: 'v1.0.0',
    targetCount: 1,
    unit: 'ngày streak',
    difficulty: 'easy',
    reward: { xp: 45, coins: 70 },
    weight: 100,
    status: 'active',
    targetAudience: 'all',
    isBonus: true,
    version: 1,
    completionRate: 91.5,
    claimRate: 85.0,
    totalCompletedCount: 1890,
    totalClaimedCount: 1755,
    lastUpdated: '2026-09-05 08:30',
    updatedBy: 'Lead Admin Hoà',
    auditNotes: 'Bonus Mission độc lập, không tính vào điều kiện mở rương Daily Chest',
  },

  // Draft Mission for testing
  {
    id: 'ms-d-07',
    code: 'MS-D-07',
    title: 'Hoàn tất 1 bài học thuộc nhóm từ C1 Advanced',
    description: 'Chinh phục danh mục từ vựng học thuật trình độ C1/C2.',
    type: 'daily',
    category: 'VOCAB_BUILDING',
    actionType: 'LEARN_NEW_WORDS',
    triggerEvent: 'FLASHCARD_REVIEWED',
    aggregationType: 'COUNT',
    completionRule: {
      uniqueWordOnly: true,
    },
    navigationParams: {
      targetScreen: 'FLASHCARD_STUDY',
      ctaLabel: 'Mở Từ C1',
    },
    minimumSupportedClientVersion: 'v1.1.0',
    targetCount: 8,
    unit: 'từ C1',
    difficulty: 'hard',
    reward: { xp: 80, coins: 120 },
    weight: 40,
    status: 'draft',
    targetAudience: 'advanced',
    isBonus: false,
    version: 1,
    completionRate: 38.0,
    claimRate: 35.0,
    totalCompletedCount: 210,
    totalClaimedCount: 195,
    lastUpdated: '2026-09-10 08:15',
    updatedBy: 'Content Specialist Mai',
    auditNotes: 'Đang chạy thử nghiệm trong sandbox trước khi đưa vào pool luân phiên',
  },

  // Scheduled Mission
  {
    id: 'ms-d-08',
    code: 'MS-D-08',
    title: 'Quét 5 đồ vật thuộc chủ đề Nhà Bếp & Ẩm Thực',
    description: 'Thử thách đặc biệt mở rộng vốn từ gia dụng hàng ngày qua camera scan.',
    type: 'daily',
    category: 'SCAN_CAPTURE',
    actionType: 'SCAN_OBJECT',
    triggerEvent: 'WORD_SCANNED_AND_SAVED',
    aggregationType: 'COUNT',
    completionRule: {
      requireSavedWord: true,
      uniqueWordOnly: true,
    },
    navigationParams: {
      targetScreen: 'CAMERA_SCAN',
      ctaLabel: 'Mở Camera AI',
    },
    minimumSupportedClientVersion: 'v1.0.0',
    targetCount: 5,
    unit: 'đồ vật bếp',
    difficulty: 'medium',
    reward: { xp: 55, coins: 90 },
    weight: 60,
    status: 'scheduled',
    targetAudience: 'all',
    isBonus: false,
    version: 1,
    validFrom: '2026-09-15 00:00',
    validTo: '2026-09-22 23:59',
    completionRate: 0,
    claimRate: 0,
    totalCompletedCount: 0,
    totalClaimedCount: 0,
    lastUpdated: '2026-09-09 15:30',
    updatedBy: 'LiveOps Campaign Lead',
  },

  // Special Event with Guardrail Override (Linked to vio-quest-01)
  {
    id: 'mission_draft_77',
    code: 'MS-EVT-01',
    title: 'Chuỗi Chinh Phục 50 Từ C1 (Thử Nghiệm Mùa Thi)',
    description: 'Nhiệm vụ đặc biệt dành cho nhóm học viên ôn thi chứng chỉ IELTS/TOEIC cấp tốc.',
    type: 'special_event',
    category: 'VOCAB_BUILDING',
    actionType: 'LEARN_NEW_WORDS',
    triggerEvent: 'FLASHCARD_REVIEWED',
    aggregationType: 'COUNT',
    completionRule: {
      uniqueWordOnly: true,
    },
    navigationParams: {
      targetScreen: 'FLASHCARD_STUDY',
      ctaLabel: 'Bắt Đầu Thử Thách C1',
    },
    minimumSupportedClientVersion: 'v1.0.0',
    targetCount: 50,
    unit: 'từ vựng C1',
    difficulty: 'hard',
    reward: { xp: 800, coins: 1500 },
    weight: 30,
    status: 'active',
    targetAudience: 'advanced',
    version: 2,
    completionRate: 22.4,
    claimRate: 20.1,
    totalCompletedCount: 140,
    totalClaimedCount: 125,
    lastUpdated: '2026-09-07 11:20',
    updatedBy: 'Super Admin Hoàng',
    auditNotes: 'Cấp quyền ngoại lệ vượt trần 1,000 Coins (ID vio-quest-01 trong Economy Guardrails)',
  },

  // ----------------------------------------------------
  // ACHIEVEMENTS & LIFETIME MILESTONES
  // ----------------------------------------------------
  {
    id: 'ms-ach-01',
    code: 'MS-ACH-01',
    title: 'Bậc Thầy Nhận Diện AI (100 Đồ Vật Thực Tế)',
    description: 'Sử dụng AI Camera quét thành công 100 đồ vật và lưu vào từ điển cá nhân.',
    type: 'achievement',
    category: 'SCAN_CAPTURE',
    actionType: 'SCAN_OBJECT',
    triggerEvent: 'WORD_SCANNED_AND_SAVED',
    aggregationType: 'COUNT',
    completionRule: {
      requireSavedWord: true,
      uniqueWordOnly: true,
    },
    navigationParams: {
      targetScreen: 'CAMERA_SCAN',
      ctaLabel: 'Mở Camera AI',
    },
    minimumSupportedClientVersion: 'v1.0.0',
    targetCount: 100,
    unit: 'đồ vật scan',
    difficulty: 'hard',
    reward: { xp: 500, coins: 800, badgeId: 'badge-ai-master' },
    weight: 50,
    status: 'active',
    targetAudience: 'all',
    version: 1,
    completionRate: 18.2,
    claimRate: 17.5,
    totalCompletedCount: 420,
    totalClaimedCount: 405,
    lastUpdated: '2026-08-15 09:00',
    updatedBy: 'Lead Admin Hoà',
  },
  {
    id: 'ms-ach-02',
    code: 'MS-ACH-02',
    title: 'Chiến Binh Bất Diệt (Chuỗi Streak 30 Ngày)',
    description: 'Học tập không gián đoạn liên tiếp trong 30 ngày để xây dựng thói quen vững chắc.',
    type: 'achievement',
    category: 'RETENTION_GAMIFICATION',
    actionType: 'MAINTAIN_STREAK',
    triggerEvent: 'STREAK_MAINTAINED',
    aggregationType: 'COUNT',
    completionRule: {},
    navigationParams: {
      targetScreen: 'STREAK_DETAIL',
      ctaLabel: 'Xem Thành Tựu Streak',
    },
    minimumSupportedClientVersion: 'v1.0.0',
    targetCount: 30,
    unit: 'ngày streak',
    difficulty: 'hard',
    reward: { xp: 600, coins: 900, badgeId: 'badge-streak-titan' },
    weight: 50,
    status: 'active',
    targetAudience: 'all',
    version: 1,
    completionRate: 12.8,
    claimRate: 12.5,
    totalCompletedCount: 290,
    totalClaimedCount: 284,
    lastUpdated: '2026-08-15 09:00',
    updatedBy: 'Lead Admin Hoà',
  },
  {
    id: 'ms-ach-03',
    code: 'MS-ACH-03',
    title: 'Kho Tàng Từ Vựng (Lưu Trữ 1,000 Từ Vựng)',
    description: 'Xây dựng kho từ điển cá nhân đạt mốc 1,000 thẻ từ phong phú.',
    type: 'achievement',
    category: 'VOCAB_BUILDING',
    actionType: 'LEARN_NEW_WORDS',
    triggerEvent: 'FLASHCARD_REVIEWED',
    aggregationType: 'COUNT',
    completionRule: {
      uniqueWordOnly: true,
    },
    navigationParams: {
      targetScreen: 'FLASHCARD_STUDY',
      ctaLabel: 'Mở Thư Viện Từ',
    },
    minimumSupportedClientVersion: 'v1.0.0',
    targetCount: 1000,
    unit: 'thẻ từ vựng',
    difficulty: 'hard',
    reward: { xp: 1000, coins: 1000, badgeId: 'badge-vocab-titan' },
    weight: 50,
    status: 'active',
    targetAudience: 'all',
    version: 1,
    completionRate: 8.4,
    claimRate: 8.2,
    totalCompletedCount: 185,
    totalClaimedCount: 181,
    lastUpdated: '2026-08-15 09:00',
    updatedBy: 'Super Admin Hoàng',
  },
  {
    id: 'ms-ach-04',
    code: 'MS-ACH-04',
    title: 'Thử Thách Flash Sale: Chiếm Lĩnh Shop Items (Archived)',
    description: 'Mua 5 vật phẩm bất kỳ trong cửa hàng Shop & Economy trong tuần lễ khai trương.',
    type: 'achievement',
    category: 'RETENTION_GAMIFICATION',
    actionType: 'EXPLORE_TOPIC',
    triggerEvent: 'TOPIC_COMPLETED',
    aggregationType: 'COUNT',
    completionRule: {},
    navigationParams: {
      targetScreen: 'HOME_HUB',
    },
    minimumSupportedClientVersion: 'v1.0.0',
    targetCount: 5,
    unit: 'vật phẩm Shop',
    difficulty: 'medium',
    reward: { xp: 200, coins: 300 },
    weight: 10,
    status: 'archived',
    targetAudience: 'all',
    version: 1,
    completionRate: 45.0,
    claimRate: 44.0,
    totalCompletedCount: 310,
    totalClaimedCount: 304,
    lastUpdated: '2026-09-01 10:00',
    updatedBy: 'Admin Gamification',
    auditNotes: 'Đã đóng sau chiến dịch khởi chạy M3',
  },
];

// ----------------------------------------------------
// DEFAULT DAILY RESET & CHEST CONFIGURATION
// ----------------------------------------------------
export const DEFAULT_DAILY_CYCLE_CONFIG: DailyCycleConfig = {
  resetTime: '00:00',
  timeZone: 'Asia/Ho_Chi_Minh (GMT+7)',
  requiredDailyCount: 5, // Chuẩn cứng 5 nhiệm vụ
  maxBonusCount: 1,      // Chuẩn cứng tối đa 1 bonus
  dailyChestReward: {
    coins: 150,
    xp: 50,
    chestName: 'Rương Kho Báu Hàng Ngày (Daily Chest)',
  },
  weightedRandomSeed: 'snap-liveops-v2-auto-rotate',
  autoRefreshPool: true,
};

// ----------------------------------------------------
// DEFAULT WEEKLY STAMP MILESTONES (BF-12F)
// ----------------------------------------------------
export const DEFAULT_WEEKLY_CONFIG: WeeklyMilestoneConfig = {
  cycleName: 'Thứ 2 → Chủ Nhật (00:00 GMT+7)',
  totalStampsMax: 7,
  milestones: [
    {
      stampsRequired: 3,
      tier: 'bronze',
      chestName: 'Rương Đồng Cần Mẫn',
      reward: {
        coins: 250,
        xp: 100,
      },
      icon: '🥉',
    },
    {
      stampsRequired: 5,
      tier: 'silver',
      chestName: 'Rương Bạc Kiên Trì',
      reward: {
        coins: 500,
        xp: 200,
        exclusiveItem: 'Booster x1.5 XP (2 giờ)',
      },
      icon: '🥈',
    },
    {
      stampsRequired: 7,
      tier: 'gold',
      chestName: 'Rương Vàng Xuất Sắc',
      reward: {
        coins: 1000,
        xp: 400,
        exclusiveItem: 'Khung Avatar Hoàng Gia & 1 Vé Streak Freeze',
      },
      icon: '👑',
    },
  ],
};

// ----------------------------------------------------
// DEFAULT GUARDRAIL POLICY
// ----------------------------------------------------
export const DEFAULT_MISSION_GUARDRAILS: MissionGuardrailConfig = {
  maxCoinsCapPerQuest: 1000,
  maxDailyPoolCoinsOutput: 2500,
  requireSuperAdminForOverride: true,
  antiSpamScanRule: true, // F-GAME-11
  strictIdempotencyKey: true,
  notifyLearnerBeforeResetHours: 2,
};

// ----------------------------------------------------
// SAMPLE GUARDRAIL VIOLATIONS
// ----------------------------------------------------
export const INITIAL_MISSION_VIOLATIONS: MissionViolation[] = [
  {
    id: 'vio-quest-01',
    missionId: 'mission_draft_77',
    missionCode: 'MS-EVT-01',
    missionTitle: 'Chuỗi Chinh Phục 50 Từ C1 (Thử Nghiệm Mùa Thi)',
    severity: 'high',
    violationType: 'COIN_CAP_EXCEEDED',
    description: 'Cấu hình phần thưởng 1,500 Coins vượt trần an toàn 1,000 Coins (+50%).',
    timestamp: '2026-09-07 11:20:45',
    status: 'whitelisted',
    mitigatedBy: 'Super Admin Hoàng',
    reason: 'Đã duyệt ngoại lệ cho chiến dịch mùa thi chứng chỉ, kiểm soát đối tượng C1',
  },
  {
    id: 'vio-quest-02',
    missionId: 'ms-d-07',
    missionCode: 'MS-D-07',
    missionTitle: 'Hoàn tất 1 bài học thuộc nhóm từ C1 Advanced',
    severity: 'medium',
    violationType: 'ANTI_CHEAT_SUSPICION',
    description: 'Phát hiện tỷ lệ claim trong 15 phút đầu sau reset vượt mức 80% bất thường.',
    timestamp: '2026-09-08 00:18:22',
    status: 'mitigated',
    mitigatedBy: 'Lead Admin Hoà',
    reason: 'Đã kiểm tra log idempotency, do lượng học viên thức đêm cày bài đồng loạt',
  },
  {
    id: 'vio-quest-03',
    missionId: 'ms-ach-03',
    missionCode: 'MS-ACH-03',
    missionTitle: 'Kho Tàng Từ Vựng (Lưu Trữ 1,000 Từ Vựng)',
    severity: 'low',
    violationType: 'COIN_CAP_EXCEEDED',
    description: 'Mức thưởng 1,000 Coins tiệm cận trần cảnh báo trần nhiệm vụ (1,000 Coins), cần giám sát faucet.',
    timestamp: '2026-09-09 09:30:10',
    status: 'active',
  },
];

// ----------------------------------------------------
// SAMPLE LEARNER PROGRESS RECORDS
// ----------------------------------------------------
export const INITIAL_LEARNER_SAMPLES: LearnerMissionProgressSample[] = [
  {
    learnerId: 'lrn-9481',
    learnerName: 'Trần Hải Nam',
    avatar: '👨‍🎓',
    email: 'hainam.tran@gmail.com',
    currentStreakDays: 14,
    dailyCompleted: 5,
    dailyTotal: 5,
    dailyChestClaimed: true,
    weeklyStamps: 6,
    unclaimedCoinsAtRisk: 0,
    lastActiveTime: '2026-09-10 14:45',
    status: 'claimed_all',
    recentEventKey: 'EVT-CLAIM-D5-20260910-9481',
  },
  {
    learnerId: 'lrn-8832',
    learnerName: 'Nguyễn Thảo Linh',
    avatar: '👩‍💼',
    email: 'linh.nguyen@outlook.com',
    currentStreakDays: 7,
    dailyCompleted: 5,
    dailyTotal: 5,
    dailyChestClaimed: false,
    weeklyStamps: 4,
    unclaimedCoinsAtRisk: 150,
    lastActiveTime: '2026-09-10 13:20',
    status: 'unclaimed_risk',
    recentEventKey: 'EVT-COMPL-D5-20260910-8832',
  },
  {
    learnerId: 'lrn-7712',
    learnerName: 'Lê Minh Khôi',
    avatar: '🧑‍💻',
    email: 'khoi.le@tech.vn',
    currentStreakDays: 28,
    dailyCompleted: 4,
    dailyTotal: 5,
    dailyChestClaimed: false,
    weeklyStamps: 5,
    unclaimedCoinsAtRisk: 60,
    lastActiveTime: '2026-09-10 15:10',
    status: 'in_progress',
    recentEventKey: 'EVT-COMPL-D4-20260910-7712',
  },
  {
    learnerId: 'lrn-6401',
    learnerName: 'Phạm Quỳnh Anh',
    avatar: '👩‍🎨',
    email: 'quynhanh.p@gmail.com',
    currentStreakDays: 3,
    dailyCompleted: 2,
    dailyTotal: 5,
    dailyChestClaimed: false,
    weeklyStamps: 2,
    unclaimedCoinsAtRisk: 0,
    lastActiveTime: '2026-09-10 11:05',
    status: 'in_progress',
  },
  {
    learnerId: 'lrn-5520',
    learnerName: 'Hoàng Quốc Bảo',
    avatar: '🧑‍🚀',
    email: 'bao.hq@fastmail.com',
    currentStreakDays: 45,
    dailyCompleted: 5,
    dailyTotal: 5,
    dailyChestClaimed: true,
    weeklyStamps: 7,
    unclaimedCoinsAtRisk: 0,
    lastActiveTime: '2026-09-10 12:40',
    status: 'claimed_all',
    recentEventKey: 'EVT-CLAIM-W7-20260910-5520',
  },
  {
    learnerId: 'lrn-3910',
    learnerName: 'Đặng Tuấn Anh',
    avatar: '🕵️',
    email: 'tuananh.d@yahoo.com',
    currentStreakDays: 0,
    dailyCompleted: 5,
    dailyTotal: 5,
    dailyChestClaimed: false,
    weeklyStamps: 1,
    unclaimedCoinsAtRisk: 280,
    lastActiveTime: '2026-09-10 01:15',
    status: 'unclaimed_risk',
    recentEventKey: 'EVT-COMPL-D5-20260910-3910',
  },
];
